Added a feature Show Weather
clubgamma/Weather-Forecaster pull request #4
Opened 2020-10-01 17:56 UTC by Yashdew

kindly refer howtorun.md and kindly generate the API from https://openweathermap.org/current .

2020-10-02 10:27 UTC, Yashdew commented
@yashpaneliya can you check my PR?

2020-10-02 13:15 UTC, vatsal30 commented
Thanks,@Yashdew, for opening the pull request! 👏

I'll be reviewing your pull request thoroughly.

Star ⭐ this project and [tweet](https://twitter.com/share?text=Contributed+to+awesome+projects+at+@club_gamma&url=https://clubgamma.github.io/hacktoberfest) about your contributions and also you can join the [discord channel of club gamma](https://discord.gg/kjnp6wU)

2020-10-02 13:26 UTC, jayskhatri commented
Hey @Yashdew please go through once [CONTRIBUTING.md](https://github.com/clubgamma/Weather-Forecaster/blob/master/CONTRIBUTING.md) and do necessary changes

Happy Hacking!🚀

2020-10-02 13:41 UTC, Yashdew commented
kindly refer howtorun.md and kindly generate the API from https://openweathermap.org/current .

 I have read the Code Of Conduct.

 I have followed all the steps of submission properly.

2020-10-02 13:42 UTC, Yashdew commented
kindly refer howtorun.md and kindly generate the API from https://openweathermap.org/current .

- [X] I have read the Code Of Conduct.
        
 - [X] I have followed all the steps of submission properly.

2020-10-02 14:11 UTC, vatsal30 commented on Yash Dewangan/templates/index.html
> +    <title>Bhai Bhai</title>
Please change title name and give meaningful name.

2020-10-02 14:27 UTC, vatsal30 requested changes

2020-10-02 14:27 UTC, vatsal30 commented on Yash Dewangan/templates/index.html
> +                <div class="field is-grouped">
Hey @Yashdew Please make the ui of this block properly.

2020-10-02 14:27 UTC, vatsal30 commented on Yash Dewangan/templates/index.html
> +                          <div class="content" >
Nothing Should be shown here when there is no input in submit box and for the very first time when site is open it showing None can you change it and make it appear when any city is submitted?

2020-10-02 14:27 UTC, vatsal30 commented on Yash Dewangan/howtorun.md
> +        pip install -r requirements.txt
You need to change the type of requirement.txt it shown error that file is missing so change the type of file and also create virtual environment for this project and make requirement.txt of that environment only.

2020-10-02 14:28 UTC, vatsal30 requested changes
PR will be merged after you update the changes

2020-10-03 12:14 UTC, Yashdew commented
@vatsal30 kindly check I have completed all the above requirements.

2020-10-04 13:00 UTC, Yashdew commented
@yashpaneliya @vatsal30 Can you guys check?

2020-10-04 19:30 UTC, vatsal30 approved these changes

2020-10-04 19:30 UTC, vatsal30 approved these changes

2020-10-04 19:34 UTC, vatsal30 approved these changes

2020-10-04 20:03 UTC, vatsal30 commented
Thanks, @Yashdew  , for opening the pull request! 👏

Star ⭐ this project and [tweet](https://twitter.com/share?text=Contributed+to+awesome+projects+at+@club_gamma&url=https://clubgamma.github.io/hacktoberfest) about your contributions and tag @clubgamma and also you can join the [discord channel of club gamma](https://discord.gg/kjnp6wU)

Ready to merge your PR!!!

2020-10-05 02:54 UTC, merged